# La librería `numpy` de Python

**Numpy** (**Num**eric **Py**thon) es una librería que dispone de varias herramientas para manejar arrays multidimensionales de forma eficiente. Esta eficiencia se debe en parte a que los arrays de `numpy`son colecciones de elementos homogéneos y de tamaño fijo, es decir, todos los elementos de un array dado tienen el mismo tipo y la colección una vez creada no se puede redimensionar. 

Para utilizar la librería **Numpy** es necesario importarla, usando típicamente el alias `np`.

In [43]:
import numpy as np

## Creación de arrays de `numpy`

Los arrays de `numpy`son objetos de la clase `np.ndarray`. Los mecanismos más habituales para crear un ejemplar de dicha clase son:
* Emplear la función `np.array()` dando como parámetro de entrada una secuencia de Python. 
* Emplear una de las funciones específicas que permiten crear arrays con valores predeterminados. Por ejemplo, `np.zeros()` crea un array nulo con las dimensiones especificadas como parámetros de entrada.
* Leer los datos de un fichero.

### Creación de arrays con la función `np.array()`

La función `np.array()` permite crear arrays a partir de una secuencia de Python generada previamente. La cantidad de dimensiones del array creado depende de la cantidad de dimensiones de la secuencia de entrada y sus elementos deben ser del mismo tipo (si hay mezcla de tipos, estos se *promocionan* al de *mayor rango*, siempre que esto sea posible). Los tipos de datos básicos para la creación de arrays son `int` (números enteros), `float` (números en coma flotante) y `complex` (números complejos), aunque también se puede emplear el tipo `string` (cadenas de caracteres). Algunos de estos tipos tienen variantes dependiendo del tamaño. 

In [44]:
array1 = np.array([1,2,3,4])                          # array1 = np.array((1,2,3,4))
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) # array2 = np.array([range(1,5),range(5,9),range(9,13)])
array3 = np.array((7.2,9.6,8,14))
array4 = np.array([7.2,9.6,8,14,'Amarillo'])
print("Array unidimensional:\n "+ str(array1))
print("Array bidimensional:\n "+ str(array2))
print("Array unidimensional (tipos promocionados):\n "+ str(array3))
print("Array unidimensional (tipos promocionados):\n "+ str(array4))

Array unidimensional:
 [1 2 3 4]
Array bidimensional:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Array unidimensional (tipos promocionados):
 [ 7.2  9.6  8.  14. ]
Array unidimensional (tipos promocionados):
 ['7.2' '9.6' '8' '14' 'Amarillo']


Los arrays de `numpy` tienen varios atributos que describen sus características. La lista completa de las propiedades de los objetos de la clase `np.ndarray`se obtiene ejecutando el comando `np.ndarray?`.
* `shape`: tupla que contiene las dimensiones del array.
* `ndim`: cantidad de dimensiones del array.
* `

In [57]:
array2.shape
array2.ndim

2

Podemos imponer el tipo de datos del array en un argumento opcional mediante la palabra reservada `dtype`. Un uso descuidado de este parámetro puede producir efectos inesperados y errores. 

In [47]:
a_int = np.array((7.2,9.6,8,14), dtype=int)
b_int = np.array([127,128,129], dtype=np.int8) # int8: integer byte (-128 to 127)
print("Array: " + str(a_int)+" Tipo: " + str(a_int.dtype))
print("Array: " + str(b_int)+" Tipo: " + str(b_int.dtype))

Array: [ 7  9  8 14] Tipo: int32
Array: [ 127 -128 -127] Tipo: int8


El tipo de datos de un array no se puede cambiar una vez que se ha creado. Como alternativa, podemos generar un nuevo array como copia de otro usando la función `n.array()` e indicando en el argumento `dtype` el nuevo tipo de datos. También disponemos del método `astype()` que crea un array a partir de otro modificando su tipo. 

In [54]:
c_int = np.array([3,5,7])
c_float = np.array(c_int, dtype=float)
c_complex = c_int.astype(complex) 

print("Array: " + str(c_int)+" Tipo: " + str(c_int.dtype))
print("Array: " + str(c_float)+" Tipo: " + str(c_float.dtype))
print("Array: " + str(c_complex)+" Tipo: " + str(c_complex.dtype))

Array: [3 5 7] Tipo: int32
Array: [3. 5. 7.] Tipo: float64
Array: [3.+0.j 5.+0.j 7.+0.j] Tipo: complex128


### Creación de arrays con funciones específicas

In [17]:
array_nulo = np.zeros((2,2))
print(array_nulo)

[[0. 0.]
 [0. 0.]]


## Propiedades de los arrays de `numpy`

https://www2.eii.uva.es/fund_inf/python/notebooks/Bibliotecas/03_Numpy/Numpy.html
https://aprendeconalf.es/docencia/python/manual/numpy/
https://numpy.org/doc/stable/user/basics.html